### ISSUE TITLE
Weird positioning of model parts

### ISSUE THREAD

**Issue by gnguralnick** [karansher/computer-graphics-kinematics#10]
When I run kinematics with the default arguments, my model looks like this

<img width="166" alt="image" src="https://user-images.githubusercontent.com/17555595/204960117-2764aa40-ef75-4d69-92c1-404c85b7d37e.png">

For some reason, the dot to control the inverse kinematic movement and the bone approximations there are shrunken.
I'm really not sure where the issue is, would love some advice.

**Comment by fares-soliman** [comment]
its cause you didnt divide ure V coordinates you generated by the w value (4th value in generated vertex vector)

**Comment by gnguralnick** [comment]
i'm doing that but it doesn't seem to change anything
when i debug, the w coordinates are all just 1 so dividing by them doesn't change anything

**Comment by gnguralnick** [comment]
fixed, i needed to set a default weight value of 0 in linear_blend_skinning rather than 1 - it was causing my vertices to get all blown up
